-- name: CreateUser :one
-- Inserts a new user. The id is generated by the caller (UUIDv7, later
-- ticket). A duplicate email surfaces as Postgres error 23505 (unique
-- violation on users.email) for the handler to map to its own 409.
INSERT INTO users (id, email, password_hash)
VALUES (sqlc.arg(id), sqlc.arg(email), sqlc.arg(password_hash))
RETURNING *;

-- name: GetUserByEmail :one
-- Login lookup. email is citext, so comparison is case-insensitive.
SELECT *
FROM users
WHERE email = sqlc.arg(email);

-- name: GetUserByID :one
SELECT *
FROM users
WHERE id = sqlc.arg(id);

-- name: MarkUserEmailVerified :one
-- Sets email_verified_at only if it was previously unset. sqlc :one returns
-- pgx.ErrNoRows when the user was already verified (or does not exist),
-- letting the caller distinguish "just verified" from "already verified".
UPDATE users
SET email_verified_at = now()
WHERE id = sqlc.arg(id)
  AND email_verified_at IS NULL
RETURNING id;

-- name: UpdateUserPassword :one
-- Used by both explicit password changes and password-reset completion.
UPDATE users
SET password_hash = sqlc.arg(password_hash),
    updated_at = now()
WHERE id = sqlc.arg(id)
RETURNING *;

-- name: LockUser :one
-- Row-level lock used to serialize password-reset token issuance per user:
-- concurrent reset requests for the same user take this lock in turn inside
-- BEGIN...COMMIT, so the issuance cap check and invalidate-then-create step
-- that follow cannot interleave across requests (#42).
SELECT id
FROM users
WHERE id = sqlc.arg(id)
FOR UPDATE;
