export const MAX_BULK_CREATE_TRANSACTIONS = 500;
export const MAX_BULK_DELETE_TRANSACTIONS = 500;
export const MAX_BULK_CREATE_BODY_BYTES = 1_000_000;
export const MAX_BULK_DELETE_BODY_BYTES = 100_000;
