// Package id generates the opaque text primary keys used by the finance
// resource tables (accounts, categories, transactions).
//
// The legacy Hono handlers generate these with @paralleldrive/cuid2's
// createId(), and the finance tables keep `text` primary keys holding
// cuid-style ids (migration 00002). Parity therefore requires the Go
// replacement to keep producing the same *format*: converging those ids on
// UUIDv7 is an observable change deferred until after the migration, and is
// already recorded as post-migration improvement 0002
// (post-migration-improvements/claude-backend-improvements/
// 0002-finance-ids-and-uuidv7-default.md). Auth tables are unaffected —
// users and token tables are real `uuid` columns and keep app-side UUIDv7
// from #41.
package id

import (
	"crypto/rand"
	"encoding/binary"
	"fmt"
	"math/big"
	"strings"
	"sync/atomic"
	"time"

	"golang.org/x/crypto/sha3"
)

// defaultLength matches @paralleldrive/cuid2's default id length, so ids
// produced here are indistinguishable in shape from the ones legacy rows
// already hold.
const defaultLength = 24

// alphabet is base36 (0-9a-z), cuid2's output alphabet.
const alphabet = "0123456789abcdefghijklmnopqrstuvwxyz"

// counter is the monotonic per-process counter cuid2 mixes into the hash so
// two ids generated in the same millisecond by the same process still
// differ. Seeded randomly at startup so separate processes do not start
// from the same value.
var counter atomic.Uint64

// fingerprint is this process's host fingerprint, computed once. cuid2 uses
// it to decorrelate ids generated by different processes that may share a
// clock.
var fingerprint string

func init() {
	counter.Store(randomUint64())
	fingerprint = randomBase36(32)
}

// New returns a new cuid2-compatible id: a random lowercase letter followed
// by 23 base36 characters derived from a SHA3-512 hash of the current time,
// a fresh random salt, the process counter, and the host fingerprint.
//
// The leading letter is what makes a cuid usable as an identifier in every
// context that rejects a leading digit, and is part of the format legacy
// ids already satisfy.
func New() string {
	firstLetter := alphabet[10+mustRandomInt(26)]

	block := fmt.Sprintf("%s%s%s%s",
		strconv36(uint64(time.Now().UnixMilli())),
		randomBase36(32),
		strconv36(counter.Add(1)),
		fingerprint,
	)

	sum := sha3.Sum512([]byte(block))
	// Interpret the digest as a big-endian integer and render it base36.
	// The leading digit of that rendering is dropped (as cuid2 does) because
	// it is biased by the digest's high bits.
	hashed := new(big.Int).SetBytes(sum[:]).Text(36)
	if len(hashed) > 1 {
		hashed = hashed[1:]
	}

	var b strings.Builder
	b.Grow(defaultLength)
	b.WriteByte(firstLetter)
	b.WriteString(hashed)
	return b.String()[:defaultLength]
}

// strconv36 renders n in base36, matching JavaScript's Number.toString(36).
func strconv36(n uint64) string {
	return new(big.Int).SetUint64(n).Text(36)
}

// randomBase36 returns a cryptographically random base36 string of length n.
func randomBase36(n int) string {
	var b strings.Builder
	b.Grow(n)
	for range n {
		b.WriteByte(alphabet[mustRandomInt(len(alphabet))])
	}
	return b.String()
}

// mustRandomInt returns a uniform random int in [0, max). It panics if the
// system CSPRNG fails, which is the same posture crypto/rand.Text and
// uuid.Must take: an id generator that silently degrades to predictable
// output is worse than a loud failure.
func mustRandomInt(max int) int {
	n, err := rand.Int(rand.Reader, big.NewInt(int64(max)))
	if err != nil {
		panic("id: crypto/rand failed: " + err.Error())
	}
	return int(n.Int64())
}

// randomUint64 seeds the counter from the CSPRNG.
func randomUint64() uint64 {
	var buf [8]byte
	if _, err := rand.Read(buf[:]); err != nil {
		panic("id: crypto/rand failed: " + err.Error())
	}
	return binary.BigEndian.Uint64(buf[:])
}
